"""Общие константы для модулей приложения."""

from __future__ import annotations

EXCLUDED_DOMAINS = {
    "avito.ru",
    "cian.ru",
    "move.ru",
    "domclick.ru",
    "irr.ru",
    "malls.ru",
    "shopandmall.ru",
    "shopsinmalls.ru",
    "be-in.ru",
    "afisha.ru",
    "kinoafisha.info",
    "93.ru",
    "yuga.ru",
    "tenchat.ru",
    "yandex.ru",
    "yandex.com",
    "yandex.com.tr",
    "maps.yandex.ru",
    "2gis.ru",
    "hh.ru",
    "flamp.ru",
    "tripadvisor.ru",
    "tripadvisor.com",
    "otzovik.com",
    "irecommend.ru",
    "youtube.com",
    "profi.ru",
    "yell.ru",
    "workspace.ru",
    "vuzopedia.ru",
    "orgpage.ru",
    "zoon.ru",
    "spr.ru",
    "blizko.ru",
    "tiendeo.ru",
    "kudago.com",
    "rating-gamedev.ru",
    "ru.wadline.com",
    "vk.com",
    "reddit.com",
    "pikabu.ru",
}

HOMEPAGE_EXCERPT_LIMIT = 40000
